// <auto-generated/>
namespace CompiledRazorTemplates.Dynamic
{
    #line hidden
    using System.Threading.Tasks;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    internal class RazorEngine_c284aa487b4b44c09665cc98a246e4cb : RazorEngine.Templating.TemplateBase<Bb.Sdk.Net.Mails.Models.MessageModelBase>
    {
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            Write(inherits);
            WriteLiteral(" System.Web.Mvc.WebViewPage\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n    <title>");
                  Write(View.Title);
            WriteLiteral("</title>\r\n</head>\r\n\r\n<body>\r\n  Bla bla\r\n</body>\r\n</html>");
        }
    }
}

