/*
 *	<auto-generated>									
 *                     									
 *	This code was generated from a template by Configuration Designer
 *	for more information see http://devtm.fr
 *                     									
 *	Changes to this file may cause incorrect behavior
 *	and will be lost if the code is regenerated.
 *						
 *	Tool created by	Gael beard gaelgael5@gmail.com Copyright 2012, 2013, 2014, 2015
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software distributed
 *  under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 *  CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 *  specific language governing permissions and limitations under the License.
 *		
 *	</auto-generated>                  					
 */

using System;
using System.ComponentModel;
using System.Configuration;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Xml;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Xml.Linq;

// suppress warning 'Missing documentation'
#pragma warning disable 1591

namespace Bb.Sdk.Net.Mails.Configurations
{

	public class SettingBD00828F04ConfigurationAttribute : SettingAttribute
	{
		public string Key { get; set; }
		public string Display { get; set; }
		public Object Value { get; set; }
		public string ValueString { get; set; }
		public Object ValueExtended { get; set; }
	}

}


namespace Bb.Sdk.Net.Mails.Configurations
{

	/// <summary>
	/// 
	/// </summary>
	/// <example>
	/// <code lang="C#">
	/// <![CDATA[
	///
	/// // get the configuration :
	/// Bb.Sdk.Net.Mails.Configurations.MailConfiguration config = Bb.Sdk.Net.Mails.Configurations.MailConfiguration.Configuration;
	///
	/// ]]>
	/// </code>
	/// </example>
	/// <example>
	/// <code lang="VB">
	/// <![CDATA[
	/// 
	/// // get the configuration :
	/// Dim Config as Bb.Sdk.Net.Mails.Configurations.MailConfiguration = Bb.Sdk.Net.Mails.Configurations.MailConfiguration.Configuration
	/// 
	/// ]]>
	/// </code>
	/// </example>
	/// <example>
	/// <code lang="Xml">
	/// <![CDATA[
	///
	/// <configuration>
	///		<section name="mailConfiguration" type="Bb.Sdk.Net.Mails.Configurations.MailConfiguration, Black.Beard.Sdk.Net.Mails" />
	/// </configSections>
	///
	/// <mailConfiguration defaultCulture="" templateFolder="""">
	///    <smtpProfiles>
	///       <Smtp name="""" hostName="""" port="25" username="""" password="""" debugMode="false" mailDebugTo="""" senderAddress="""" senderName="""" bccAddress="""" enabledSsl="false" timeOut="60000" deliveryMethod="Network" deliveryFormat="International" minPool="2" maxPool="5" pickupDirectoryLocation="""" />
	///
	///    </smtpProfiles>
	///
	/// </mailConfiguration>
	///
	/// </configuration>
	/// ]]>
	/// </code>
	/// </example>
	/// <remarks>
	/// generated by Configuration Designer
	/// for more information on the tool, see http://devtm.fr
	/// </remarks>
	[System.Runtime.InteropServices.Guid("EBD00828-F04F-420B-8952-5A94527B0C8C")]
	public partial class MailConfiguration : System.Configuration.ConfigurationSection, IXmlSerializable
	{


		#region Common


		/// <summary>
		/// Used to initialize a default set of values for the <see cref="MailConfiguration" /> 
		/// object.
		/// </summary>
		public void InitializeDefaultValue()
		{
			base.InitializeDefault();
		}


		/// <summary>
		/// Indicates whether this configuration element has been modified since it was
		/// last saved or loaded, when implemented in a derived class.
		/// </summary>
		/// <returns><c>true</c> if the element has been modified; otherwise, <c>false</c>.</returns>
		public bool ObjetctIsModified()
		{
			return base.IsModified();
		}


		/// <summary>
		/// Gets a value indicating whether the <see cref="MailConfiguration" />
		/// object is read-only.
		/// </summary>
		/// <returns><c>true</c> if the MailConfiguration object is read-only otherwise, <c>false</c>.</returns>
		public bool ObjetctIsReadOnly()
		{
			return base.IsReadOnly();
		}


		#region IXmlSerializable
		

		/// <summary>													
		/// Updates the <see cref="MailConfiguration" /> with the values from an <see cref="XmlReader" />.													
		/// </summary>													
		/// <param name="reader">The <see cref="XmlReader" /> that reads the configuration source located at the element that describes the configuration section.</param>													
		public void ReadXml(XmlReader reader)
		{
			if (reader == null) 
                throw new ArgumentNullException("reader");
			DeserializeSection(reader);			
		}


		/// <summary>													
		/// Writes the <see cref="MailConfiguration" /> values as an XML element to an <see cref="XmlWriter" />.													
		/// </summary>													
		/// <param name="writer">The <see cref="XmlWriter" /> that writes to the configuration source.</param>													
		public void WriteXml(XmlWriter writer)
		{
			if (writer == null) throw new ArgumentNullException("writer");

			String serialized = SerializeSection(this, "MailConfiguration", ConfigurationSaveMode.Full);
			writer.WriteRaw(serialized);
		}


		/// <summary>													
		/// Returns the XML schema for the configuration section.													
		/// </summary>													
		/// <returns>A string with the XML schema, or <see langword="null" /> (<b>Nothing</b> 													
		/// in Visual Basic) if there is no schema.</returns>													
		public XmlSchema GetSchema()
		{
			return null;
		}


		#endregion IXmlSerializable

		
        /// <summary>
        /// Loads the file.
        /// </summary>
        /// <param name="filename">The filename.</param>
        /// <returns></returns>
        public static MailConfiguration LoadFile(string filename)
        {

            if (string.IsNullOrEmpty(filename))
                throw new InvalidOperationException("argument filename can't be null.");

            if (!File.Exists(filename))
                throw new System.IO.FileLoadException(string.Format("missing file {0}", filename));

            MailConfiguration config = new MailConfiguration();
            XElement x = XElement.Load(filename);

            XElement x2;
            if (x.Name.LocalName != MailConfiguration.DefaultName)
                x2 = x.Element(MailConfiguration.DefaultName);
            else
                x2 = x;

            StringReader sReader = new StringReader(x2.ToString());
            XmlReader reader = XmlReader.Create(sReader);
            config.ReadXml(reader);
            return config;

        }


		public static MailConfiguration LoadConfiguration(string filename)
        {

            if (string.IsNullOrEmpty(filename))
                throw new InvalidOperationException("argument filename can't be null.");

            if (!File.Exists(filename))
                throw new System.IO.FileLoadException(string.Format("missing file {0}", filename));

            var filemap = new ExeConfigurationFileMap() { ExeConfigFilename = filename };
            var conf = System.Configuration.ConfigurationManager.OpenMappedExeConfiguration(filemap, ConfigurationUserLevel.None);

            MailConfiguration config = conf.GetSection(MailConfiguration.DefaultName) as MailConfiguration;

            return config;

        }

        public void WriteFile(string filename)
        {

            if (string.IsNullOrEmpty(filename))
                throw new InvalidOperationException("argument filename can't be null.");

            using (StringWriter sWriter = new StringWriter())
            {

                XmlWriter writer = XmlWriter.Create(sWriter);
                this.WriteXml(writer);
                writer.Flush();

                XElement x = XElement.Parse(sWriter.ToString());
                x.Name = XName.Get(MailConfiguration.DefaultName);
                x.Save(filename);

            }

        }

        /// <summary>
        /// Writes the file on the disk.
        /// </summary>
        /// <param name="filename">The filename.</param>
        public void WriteConfiguration(string filename)
        {
            FileInfo f = new FileInfo(filename);
            if (f.Exists)
                f.Delete();
            var filemap = new ExeConfigurationFileMap() { ExeConfigFilename = f.FullName };
            var conf = System.Configuration.ConfigurationManager.OpenMappedExeConfiguration(filemap, ConfigurationUserLevel.None);

			var instance = this.CurrentConfiguration == null 
                ? this 
                : this.AsWritable();
            
            conf.Sections.Add(MailConfiguration.DefaultName, instance);
            conf.Save(ConfigurationSaveMode.Minimal);
        }

		/// <summary>
		/// Override the current <see cref="MailConfiguration" /> object with the parameters from the element.
		/// </summary>
		/// <returns></returns>
		public void OverrideFrom(MailConfiguration element)
		{

			using (StringWriter sWriter = new StringWriter())
			{

				XmlWriter writer = XmlWriter.Create(sWriter);
				element.WriteXml(writer);
				writer.Flush();
				
				StringReader sReader = new StringReader(sWriter.ToString());
				XmlReader reader = XmlReader.Create(sReader);
				this.ReadXml(reader);
				
			}

		}

		#endregion Common

		
		
		public const string DefaultName = "mailConfiguration";

		private static MailConfiguration _configuration;
		public static MailConfiguration Configuration 
		{ 
			get 
			{ 
				return _configuration ?? (_configuration = System.Configuration.ConfigurationManager.GetSection(DefaultName) as MailConfiguration); 
			} 
			set
			{
				_configuration = value;
			}
		}

	
		/// <summary>
		/// Gets a writable <see cref="MailConfiguration" /> object with the parameters from the current.
		/// </summary>
		/// <returns></returns>
		public MailConfiguration AsWritable()
		{
			
			MailConfiguration config = new MailConfiguration();

			using (StringWriter sWriter = new StringWriter())
			{

				XmlWriter writer = XmlWriter.Create(sWriter);
				this.WriteXml(writer);
				writer.Flush();

				StringReader sReader = new StringReader(sWriter.ToString());
				XmlReader reader = XmlReader.Create(sReader);
				config.ReadXml(reader);
				
			}
			return config;

		}


		/// <summary>
		/// Gets the runtime<see cref="MailConfiguration" /> object.
		/// </summary>
		/// <returns></returns>
		public MailConfiguration GetRuntimeMailConfigurationSection()
		{
			MailConfiguration ret = base.GetRuntimeObject() as MailConfiguration;
			return ret;
		}    

	
		#region Attributes
			
		#region Default Culture

		/// <summary>
		/// Default Culture
		/// </summary>
		[DisplayName("Default Culture")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(DefaultCultureConst, IsRequired = false)]
		public Bb.Sdk.Net.Mails.Configurations.CultureEnum DefaultCulture
		{
			get
			{
				return (Bb.Sdk.Net.Mails.Configurations.CultureEnum)this[DefaultCultureConst]; 
			}
			set
			{
				this[DefaultCultureConst] = value;
			}
		}
		public const string DefaultCultureConst = "defaultCulture";

		#endregion
					
		#region Template Folder

		/// <summary>
		/// Template Folder
		/// </summary>
		[DisplayName("Template Folder")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(TemplateFolderConst, IsRequired = false, DefaultValue =  "")]
		public System.String TemplateFolder
		{
			get
			{
				return (System.String)this[TemplateFolderConst]; 
			}
			set
			{
				this[TemplateFolderConst] = value;
			}
		}
		public const string TemplateFolderConst = "templateFolder";

		#endregion
			
		#endregion Attributes
	
		#region Refs
			
		#region Smtp Profiles

		/// <summary>
		/// Smtp Profiles
		/// </summary>
		/// <returns>		
		/// Objet <see cref="Bb.Sdk.Net.Mails.Configurations.ServiceMailProfileCollection" />.");
		/// </returns>
		[DisplayName("Smtp Profiles")]
		[Description("")]
		[Category("Misc")]
		public Bb.Sdk.Net.Mails.Configurations.ServiceMailProfileCollection SmtpProfiles
		{
			get { return (Bb.Sdk.Net.Mails.Configurations.ServiceMailProfileCollection)this[SmtpProfilesConst]; }            
		}
		public const string SmtpProfilesConst = "smtpProfiles";

		#endregion

		#endregion Refs
		
		 
		/// <summary>
		/// Checks the specified test.
		/// </summary>
		/// <param name="tests">The type.</param>
		public List<MailConfigurationCheck.Error> Check(params Type[] tests)
		{

			List<MailConfigurationCheck.Error> Errors = new List<MailConfigurationCheck.Error>();            
			
			bool throwOnMessage = false;
			foreach (Type typeTest in tests)
			{
				
				MailConfigurationCheck test 
					= Activator.CreateInstance(typeTest) as MailConfigurationCheck;

				test.Errors = Errors;

				test.Check(this);

				throwOnMessage = throwOnMessage | test._throwOnMessage;

			}

			if (throwOnMessage)
				throw new MailConfigurationCheck.MailConfigurationException("MailConfiguration is in error. please see the list of error in this exception") { Errors = Errors, Config = this };

			return Errors;

		}
		
		
	}


	  
	#region Checks
	
	/// <summary>
	/// Test on  MailConfiguration(
	/// </summary>
	public abstract class  MailConfigurationCheck
	{

		internal bool _throwOnMessage = false;

		/// <summary>
		/// run the test on the specified config.
		/// </summary>
		/// <param name="config">The config.</param>
		protected internal abstract void Check( MailConfiguration config);


		/// <summary>
		/// Gets or sets the errors.
		/// </summary>
		/// <value>The errors.</value>
		public System.Collections.Generic.List<Error> Errors { get; set; }


		/// <summary>
		/// Logs the error.
		/// </summary>
		/// <param name="error">The error.</param>
        /// <param name="throwOnMessage">if set to <c>true</c> [throw on message].</param>
		/// <param name="sender">The sender.</param>
		/// <param name="message">The message.</param>
		/// <param name="args">The args.</param>
		protected internal void Log(string error, bool throwOnMessage, ConfigurationElement sender, string message, params object[] args)
		{
			_throwOnMessage = throwOnMessage || _throwOnMessage;
			message = string.Format(message, args);
			Errors.Add(new Error() { Message = message, Sender = sender, ThrowOnMessage = throwOnMessage });
		}


		/// <summary>
		/// message log
		/// </summary>
		public class Error
		{

			/// <summary>
			/// Gets or sets the message.
			/// </summary>
			/// <value>The message.</value>
			public string Message { get; set; }

			/// <summary>
			/// Gets or sets the sender.
			/// </summary>
			/// <value>The sender.</value>
			public ConfigurationElement Sender { get; set; }

			/// <summary>
			/// Gets or sets a value indicating whether [throw on message].
			/// </summary>
			/// <value><c>true</c> if [throw on message]; otherwise, <c>false</c>.</value>
			public bool ThrowOnMessage { get; set; }

		}



	/// <summary>
	/// Exception for the missing MailConfiguration configuration
	/// </summary>
	[Serializable]
	public class MissingMailConfigurationException : Exception
	{


		/// <summary>
		/// Initializes a new instance of the <see cref="MissingMailConfigurationException"/> class.
		/// </summary>
		public MissingMailConfigurationException() { }


		/// <summary>
		/// Initializes a new instance of the <see cref="MissingMailConfigurationException"/> class.
		/// </summary>
		/// <param name="message">The message that describes the error.</param>
		public MissingMailConfigurationException(string message) : base(message) { }


		/// <summary>
		/// Initializes a new instance of the <see cref="MissingMailConfigurationException"/> class.
		/// </summary>
		/// <param name="message">The message that describes the error.</param>
		/// <param name="inner">The exception that is the cause of the current exception, or a null reference (Nothing in Visual Basic) if no inner exception is specified.</param>
		public MissingMailConfigurationException(string message, Exception inner) : base(message, inner) { }

		/// <summary>
		/// Initializes a new instance of the <see cref="MissingMailConfigurationException"/> class.
		/// </summary>
		/// <param name="info">The <see cref="T:System.Runtime.Serialization.SerializationInfo"/> that holds the serialized object data about the exception being thrown.</param>
		/// <param name="context">The <see cref="T:System.Runtime.Serialization.StreamingContext"/> that contains contextual information about the source or destination.</param>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="info"/> parameter is null. </exception>
		/// <exception cref="T:System.Runtime.Serialization.SerializationException">The class name is null or <see cref="P:System.Exception.HResult"/> is zero (0). </exception>
		protected MissingMailConfigurationException(
		  System.Runtime.Serialization.SerializationInfo info,
		  System.Runtime.Serialization.StreamingContext context)
			: base(info, context) { }
	}


		/// <summary>
		/// Exception for the check MailConfiguration configuration
		/// </summary>
		[Serializable]
		public class MailConfigurationException : Exception
		{

			/// <summary>
			/// Initializes a new instance of the <see cref="MailConfigurationException"/> class.
			/// </summary>
			public  MailConfigurationException() { }
			
			
			/// <summary>
			/// Initializes a new instance of the <see cref="MailConfigurationException"/> class.
			/// </summary>
			/// <param name="message">The message.</param>
			public MailConfigurationException(string message) : base(message) { }
			
			
			/// <summary>
			/// Initializes a new instance of the <see cref="MailConfigurationException"/> class.
			/// </summary>
			/// <param name="message">The message.</param>
			/// <param name="inner">The inner.</param>
			public MailConfigurationException(string message, Exception inner) : base(message, inner) { }
			
			
			/// <summary>
			/// Initializes a new instance of the <see cref="MailConfigurationException"/> class.
			/// </summary>
			/// <param name="info">The <see cref="T:System.Runtime.Serialization.SerializationInfo"/> that holds the serialized object data about the exception being thrown.</param>
			/// <param name="context">The <see cref="T:System.Runtime.Serialization.StreamingContext"/> that contains contextual information about the source or destination.</param>
			/// <exception cref="T:System.ArgumentNullException">
			/// The <paramref name="info"/> parameter is null.
			/// </exception>
			/// <exception cref="T:System.Runtime.Serialization.SerializationException">
			/// The class name is null or <see cref="P:System.Exception.HResult"/> is zero (0).
			/// </exception>
			protected MailConfigurationException(
			  System.Runtime.Serialization.SerializationInfo info,
			  System.Runtime.Serialization.StreamingContext context)
				: base(info, context) { }


			/// <summary>
			/// Get the list of error
			/// </summary>
			public List<MailConfigurationCheck.Error> Errors { get; internal set; }


			/// <summary>
			/// Gets the config.
			/// </summary>
			/// <value>The config.</value>
			public MailConfiguration Config { get; internal set; }


			/// <summary>
			/// Gets the full description on errors.
			/// </summary>
			/// <value>The full error description.</value>
			public string FullErrorDescription
			{
				get 
				{
					StringBuilder s = new StringBuilder(Message);

					foreach (MailConfigurationCheck.Error item in Errors)
						s.AppendLine(item.Sender.GetType().FullName + "  " + item.Message);

					return s.ToString();
				}
			}


		}
		
	}

	#endregion Checks
	
}
	
namespace Bb.Sdk.Net.Mails.Configurations
{

	/// <summary>
	/// 
	/// </summary>
	/// <remarks>
	/// generated by Configuration Designer
	/// for more information on the tool, see http://devtm.fr
	/// </remarks>
	public partial class ServiceMailProfileCollection : System.Configuration.ConfigurationElementCollection
	{


				
		/// <summary>
		/// Ctor
		/// </summary>
		public ServiceMailProfileCollection() { }		

		/// <summary>
		/// return Configuration Element Collection Type <see cref="T:AddRemoveClearMap" />
		/// </summary>
		public override ConfigurationElementCollectionType CollectionType
		{
			get { return ConfigurationElementCollectionType.AddRemoveClearMap ;}
		}


		/// <summary>
		/// Return the attribute element 'name' in the xml
		/// </summary>
		protected override string ElementName { get { return "name"; } }


		/// <summary>
		/// Create a new <see cref="Bb.Sdk.Net.Mails.Configurations.SmtpProfile" /> for the current collection
		/// </summary>
		/// <returns></returns>
		protected override System.Configuration.ConfigurationElement CreateNewElement() { return new Bb.Sdk.Net.Mails.Configurations.SmtpProfile(); }


		/// <summary>
		/// return the key for specified element
		/// </summary>
		/// <param name="element">Bb.Sdk.Net.Mails.Configurations.SmtpProfile</param>
		/// <returns>as Bb.Sdk.Net.Mails.Configurations.SmtpProfile</returns>
		protected override object GetElementKey(System.Configuration.ConfigurationElement element) { return ((Bb.Sdk.Net.Mails.Configurations.SmtpProfile)element).Name; }


		/// <summary>
		/// Add a new item
		/// </summary>
		/// <param name="element">the Bb.Sdk.Net.Mails.Configurations.SmtpProfile to add</param>
		/// <returns>the added Bb.Sdk.Net.Mails.Configurations.SmtpProfile in parameter</returns>
		public Bb.Sdk.Net.Mails.Configurations.SmtpProfile Add(Bb.Sdk.Net.Mails.Configurations.SmtpProfile element) 
		{ 
			BaseAdd(element); 
			return element;
		}

		/// <summary>
		/// remove the item specified by this key
		/// </summary>
		/// <param name="key">as a System.String type</param>
		public void Remove(System.String key) { BaseRemove(key); }


		/// <summary>
		/// Clear the collection
		/// </summary>
		public void Clear() { BaseClear(); }

		/// <summary>
		/// return the item specified by this key
		/// </summary>
		/// <param name="index">as a System.String type</param>
		public new Bb.Sdk.Net.Mails.Configurations.SmtpProfile this[System.String index] 
		{ 
			get { return (Bb.Sdk.Net.Mails.Configurations.SmtpProfile)BaseGet(index); } 			
		}


		/// <summary>
		/// return the item specified by this index in the collection
		/// </summary>
		/// <param name="index">as a System.String type</param>
		public Bb.Sdk.Net.Mails.Configurations.SmtpProfile this[int index] 
		{
			get { return (Bb.Sdk.Net.Mails.Configurations.SmtpProfile)BaseGet(index); } 
			set
			{
				if (BaseGet(index) != null)
					BaseRemoveAt(index);
				BaseAdd(index, value);
			}
		}


		/// <summary>
		/// Indicates whether the specified <see cref="Bb.Sdk.Net.Mails.Configurations.SmtpProfile" /> exists in the Collection.
		/// </summary>
		/// <param name="key">The key of the element to verify.</param>
		/// <returns><c>true</c> if the element exists in the collection; otherwise, <c>false</c>. The default is <c>false</c>.</returns>
		public bool Contains(System.String key)
		{
			return base.BaseGet(key) != null;
		}


		/// <summary>
		/// Gets a value indicating whether the specified <see cref="Bb.Sdk.Net.Mails.Configurations.SmtpProfile" /> can be removed from the Collection.
		/// </summary>
		/// <param name="element">The element to check.</param>
		/// <returns><c>true</c> if the specified Bb.Sdk.Net.Mails.Configurations.SmtpProfile can be removed from this Collection; otherwise, <c>false</c>. The default is <c>true</c>.</returns>
		public bool IsRemovable(Bb.Sdk.Net.Mails.Configurations.SmtpProfile element)
		{
			return base.IsElementRemovable(element);
		}


		/// <summary>
		/// The index of the specified <see cref="Bb.Sdk.Net.Mails.Configurations.SmtpProfile" />.
		/// </summary>
		/// <param name="element">The Bb.Sdk.Net.Mails.Configurations.SmtpProfile for the specified index location.</param>
		/// <returns>The index of the specified Bb.Sdk.Net.Mails.Configurations.SmtpProfile; otherwise, -1.</returns>
		public int IndexOf(Bb.Sdk.Net.Mails.Configurations.SmtpProfile element)
		{
			return base.BaseIndexOf(element);
		}


		/// <summary>
		/// Gets the key for the <see cref="Bb.Sdk.Net.Mails.Configurations.SmtpProfile" /> at the specified index location.
		/// </summary>
		/// <param name="index">The index location for the Bb.Sdk.Net.Mails.Configurations.SmtpProfile.</param>
		/// <returns>The key for the specified Bb.Sdk.Net.Mails.Configurations.SmtpProfile.</returns>
		public string GetKey(int index)
		{
			return base.BaseGetKey(index).ToString();
		}


		/// <summary>
		/// The index of the specified <see cref="Bb.Sdk.Net.Mails.Configurations.SmtpProfile" />.
		/// </summary>
		/// <param name="key">The Bb.Sdk.Net.Mails.Configurations.SmtpProfile for the specified index location.</param>
		/// <returns>The index of the specified Bb.Sdk.Net.Mails.Configurations.SmtpProfile; otherwise, -1.</returns>
		public bool IsRemoved(System.String key)
		{
			return base.BaseIsRemoved(key);
		}

		
	}


	
}
	
namespace Bb.Sdk.Net.Mails.Configurations
{

	/// <summary>
	/// 
	/// </summary>
	/// <remarks>
	/// generated by Configuration Designer
	/// for more information on the tool, see http://devtm.fr
	/// </remarks>
	public partial class SmtpProfile : System.Configuration.ConfigurationElement
	{


			
		#region Attributes
			
		#region Name

		/// <summary>
		/// Name
		/// </summary>
		[DisplayName("Name")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(NameConst, IsRequired = false, DefaultValue =  "")]
		public System.String Name
		{
			get
			{
				return (System.String)this[NameConst]; 
			}
			set
			{
				this[NameConst] = value;
			}
		}
		public const string NameConst = "name";

		#endregion
					
		#region Host Name

		/// <summary>
		/// Host Name
		/// </summary>
		[DisplayName("Host Name")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(HostNameConst, IsRequired = false, DefaultValue =  "")]
		public System.String HostName
		{
			get
			{
				return (System.String)this[HostNameConst]; 
			}
			set
			{
				this[HostNameConst] = value;
			}
		}
		public const string HostNameConst = "hostName";

		#endregion
					
		#region Port

		/// <summary>
		/// Port
		/// </summary>
		[DisplayName("Port")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(PortConst, IsRequired = false, DefaultValue = 25)]
		public System.Int32 Port
		{
			get
			{
				return (System.Int32)this[PortConst]; 
			}
			set
			{
				this[PortConst] = value;
			}
		}
		public const string PortConst = "port";

		#endregion
					
		#region Username

		/// <summary>
		/// Username
		/// </summary>
		[DisplayName("Username")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(UsernameConst, IsRequired = false, DefaultValue =  "")]
		public System.String Username
		{
			get
			{
				return (System.String)this[UsernameConst]; 
			}
			set
			{
				this[UsernameConst] = value;
			}
		}
		public const string UsernameConst = "username";

		#endregion
					
		#region Password

		/// <summary>
		/// Password
		/// </summary>
		[DisplayName("Password")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(PasswordConst, IsRequired = false, DefaultValue =  "")]
		public System.String Password
		{
			get
			{
				return (System.String)this[PasswordConst]; 
			}
			set
			{
				this[PasswordConst] = value;
			}
		}
		public const string PasswordConst = "password";

		#endregion
					
		#region Debug Mode

		/// <summary>
		/// Debug Mode
		/// </summary>
		[DisplayName("Debug Mode")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(DebugModeConst, IsRequired = false, DefaultValue = false)]
		public System.Boolean DebugMode
		{
			get
			{
				return (System.Boolean)this[DebugModeConst]; 
			}
			set
			{
				this[DebugModeConst] = value;
			}
		}
		public const string DebugModeConst = "debugMode";

		#endregion
					
		#region Mail Debug To

		/// <summary>
		/// Mail Debug To
		/// </summary>
		[DisplayName("Mail Debug To")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(MailDebugToConst, IsRequired = false, DefaultValue =  "")]
		public System.String MailDebugTo
		{
			get
			{
				return (System.String)this[MailDebugToConst]; 
			}
			set
			{
				this[MailDebugToConst] = value;
			}
		}
		public const string MailDebugToConst = "mailDebugTo";

		#endregion
					
		#region Sender Address

		/// <summary>
		/// Sender Address
		/// </summary>
		[DisplayName("Sender Address")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(SenderAddressConst, IsRequired = false, DefaultValue =  "")]
		public System.String SenderAddress
		{
			get
			{
				return (System.String)this[SenderAddressConst]; 
			}
			set
			{
				this[SenderAddressConst] = value;
			}
		}
		public const string SenderAddressConst = "senderAddress";

		#endregion
					
		#region Sender Name

		/// <summary>
		/// Sender Name
		/// </summary>
		[DisplayName("Sender Name")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(SenderNameConst, IsRequired = false, DefaultValue =  "")]
		public System.String SenderName
		{
			get
			{
				return (System.String)this[SenderNameConst]; 
			}
			set
			{
				this[SenderNameConst] = value;
			}
		}
		public const string SenderNameConst = "senderName";

		#endregion
					
		#region Bcc Address

		/// <summary>
		/// Bcc Address
		/// </summary>
		[DisplayName("Bcc Address")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(BccAddressConst, IsRequired = false, DefaultValue =  "")]
		public System.String BccAddress
		{
			get
			{
				return (System.String)this[BccAddressConst]; 
			}
			set
			{
				this[BccAddressConst] = value;
			}
		}
		public const string BccAddressConst = "bccAddress";

		#endregion
					
		#region Enabled Ssl

		/// <summary>
		/// Enabled Ssl
		/// </summary>
		[DisplayName("Enabled Ssl")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(EnabledSslConst, IsRequired = false, DefaultValue = false)]
		public System.Boolean EnabledSsl
		{
			get
			{
				return (System.Boolean)this[EnabledSslConst]; 
			}
			set
			{
				this[EnabledSslConst] = value;
			}
		}
		public const string EnabledSslConst = "enabledSsl";

		#endregion
					
		#region Time Out

		/// <summary>
		/// Time Out
		/// </summary>
		[DisplayName("Time Out")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(TimeOutConst, IsRequired = false, DefaultValue = 60000)]
		public System.Int32 TimeOut
		{
			get
			{
				return (System.Int32)this[TimeOutConst]; 
			}
			set
			{
				this[TimeOutConst] = value;
			}
		}
		public const string TimeOutConst = "timeOut";

		#endregion
					
		#region Delivery Method

		/// <summary>
		/// Delivery Method
		/// </summary>
		[DisplayName("Delivery Method")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(DeliveryMethodConst, IsRequired = false, DefaultValue = System.Net.Mail.SmtpDeliveryMethod.Network)]
		public System.Net.Mail.SmtpDeliveryMethod DeliveryMethod
		{
			get
			{
				return (System.Net.Mail.SmtpDeliveryMethod)this[DeliveryMethodConst]; 
			}
			set
			{
				this[DeliveryMethodConst] = value;
			}
		}
		public const string DeliveryMethodConst = "deliveryMethod";

		#endregion
					
		#region Delivery Format

		/// <summary>
		/// Delivery Format
		/// </summary>
		[DisplayName("Delivery Format")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(DeliveryFormatConst, IsRequired = false, DefaultValue = System.Net.Mail.SmtpDeliveryFormat.International)]
		public System.Net.Mail.SmtpDeliveryFormat DeliveryFormat
		{
			get
			{
				return (System.Net.Mail.SmtpDeliveryFormat)this[DeliveryFormatConst]; 
			}
			set
			{
				this[DeliveryFormatConst] = value;
			}
		}
		public const string DeliveryFormatConst = "deliveryFormat";

		#endregion
					
		#region Min Pool

		/// <summary>
		/// Min Pool
		/// </summary>
		[DisplayName("Min Pool")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(MinPoolConst, IsRequired = false, DefaultValue = 2)]
		public System.Int32 MinPool
		{
			get
			{
				return (System.Int32)this[MinPoolConst]; 
			}
			set
			{
				this[MinPoolConst] = value;
			}
		}
		public const string MinPoolConst = "minPool";

		#endregion
					
		#region Max Pool

		/// <summary>
		/// Max Pool
		/// </summary>
		[DisplayName("Max Pool")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(MaxPoolConst, IsRequired = false, DefaultValue = 5)]
		public System.Int32 MaxPool
		{
			get
			{
				return (System.Int32)this[MaxPoolConst]; 
			}
			set
			{
				this[MaxPoolConst] = value;
			}
		}
		public const string MaxPoolConst = "maxPool";

		#endregion
					
		#region Pickup Directory Location

		/// <summary>
		/// Pickup Directory Location
		/// </summary>
		[DisplayName("Pickup Directory Location")]
		[Description("")]
		[Category("Misc")]
		[ConfigurationProperty(PickupDirectoryLocationConst, IsRequired = false, DefaultValue =  "")]
		public System.String PickupDirectoryLocation
		{
			get
			{
				return (System.String)this[PickupDirectoryLocationConst]; 
			}
			set
			{
				this[PickupDirectoryLocationConst] = value;
			}
		}
		public const string PickupDirectoryLocationConst = "pickupDirectoryLocation";

		#endregion
			
		#endregion Attributes
		

	}


	
}
		


